### ISSUE TITLE
Possible wrong type generation from Swagger schema

### ISSUE THREAD

**Issue by tokict** [ovotech/laminar#127]
```yaml
MetaData:
      type: object
```

should generate  
```typescript
[key: any]: unknown;
```
or similar as object property type

And 
```yaml
    MetaData:
      type: object
      additionalProperties:
        type: string
```
should generate object with strings for keys [(per docs)](https://swagger.io/docs/specification/data-models/dictionaries/) but it creates ANY

The only thing that works is 
```yaml
 MetaData:
      type: object
      properties: false
      additionalProperties:
        type: string
``` 
but properties:false is not documented in the Swagger docs. 
Is this expected behavior?
